version: '3'
services:
  server:
    build: ./server
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge