version: '3'
services:
  my-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - my-network
    ports:
      - 8080:8080

  my-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - my-network
    depends_on:
      - my-server

networks:
  my-network:
    driver: bridge