version: '3'
services:
  server:
    build: ./server
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - mynetwork

  client-spam:
    build: ./client
    depends_on:
      - server
    entrypoint: [ "./main", "--empty-request","3" ]
    networks:
      - mynetwork

  client-delay:
    build: ./client
    depends_on:
      - server
    entrypoint: [ "./main", "--delay","5s" ]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge